# Generated by Django 4.2.13 on 2024-06-12 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('quota', models.PositiveBigIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('last_time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
