# Generated by Django 4.2.13 on 2024-06-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin'),
        ('news_search_api', '0007_alter_searchresult_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchkeyword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
