# Generated by Django 4.2.13 on 2024-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_search_api', '0002_searchresult_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
